services:
  postgres:
    image: postgres:17
    container_name: mediflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: mediflow
      POSTGRES_USER: mediflow_user
      POSTGRES_PASSWORD: mediflow_password

    ports:
      - "5432:5432"

    volumes:
      - mediflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediflow_user -d mediflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.3.1-management
    container_name: mediflow-rabbitmq
    hostname: mediflow-rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: mediflow_user
      RABBITMQ_DEFAULT_PASS: mediflow_password

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - mediflow_rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  mediflow_postgres_data:
  mediflow_rabbitmq_data:
